#!/usr/bin/env python3
"""Generate MkDocs API stub pages and navigation from ``src/agentTaxonomy``."""

from __future__ import annotations

import re
import sys
from pathlib import Path

PACKAGE_NAME = "agentTaxonomy"
GENERATED_BANNER = "<!-- Auto-generated by scripts/generate_api_stubs.py. Do not edit manually. -->\n\n"

# Display titles for modules where title case is not enough.
MODULE_TITLES: dict[str, str] = {
    "cli": "CLI",
    "generate": "Generation",
}

NAV_START = "# autogenerated-api-nav-start"
NAV_END = "# autogenerated-api-nav-end"


def discover_modules(package_dir: Path) -> list[str]:
    """Return top-level module names under ``agentTaxonomy`` (packages and .py modules).

    Args:
        package_dir: Path to ``src/agentTaxonomy``.

    Returns:
        Sorted list of module basenames (for example ``catalog``, ``judge``).
    """
    modules: list[str] = []
    for entry in sorted(package_dir.iterdir()):
        if entry.name.startswith("_") or entry.name.startswith("."):
            continue
        if entry.is_file() and entry.suffix == ".py" and entry.name != "__init__.py":
            modules.append(entry.stem)
        elif entry.is_dir() and (entry / "__init__.py").is_file():
            modules.append(entry.name)
    return modules


def module_title(module: str) -> str:
    """Human-readable nav title for a module basename."""
    return MODULE_TITLES.get(module, module.replace("_", " ").title())


def module_dotted_name(module: str) -> str:
    """Fully qualified import path for mkdocstrings."""
    return f"{PACKAGE_NAME}.{module}"


def write_stub(api_dir: Path, module: str) -> Path:
    """Write a single API stub markdown file.

    Args:
        api_dir: ``docs/api`` directory.
        module: Module basename (for example ``scoring``).

    Returns:
        Path to the written file.
    """
    title = module_title(module)
    path = api_dir / f"{module}.md"
    body = (
        f"{GENERATED_BANNER}"
        f"# {title}\n\n"
        f"::: {module_dotted_name(module)}\n"
    )
    if module == "judge":
        body = (
            f"{GENERATED_BANNER}"
            "# Judge\n\n"
            "Soft-review evaluation: binary rubric grading via LLM or offline heuristics.\n\n"
            f"::: {module_dotted_name(module)}\n"
        )
    path.write_text(body, encoding="utf-8")
    return path


def write_index(api_dir: Path, modules: list[str]) -> Path:
    """Write the API overview page with a module table."""
    rows = [
        f"| [`{module_dotted_name(m)}`]({m}.md) | {module_title(m)} |"
        for m in modules
    ]
    content = (
        f"{GENERATED_BANNER}"
        "# API Reference\n\n"
        "Python API for catalog management, run generation, trace I/O, and multi-layer scoring.\n\n"
        "| Module | Description |\n"
        "|--------|-------------|\n"
        + "\n".join(rows)
        + "\n\n"
        "Install from the repository root:\n\n"
        "```bash\n"
        "uv sync\n"
        "```\n\n"
        "For development without installation, set `PYTHONPATH=src`.\n"
    )
    path = api_dir / "index.md"
    path.write_text(content, encoding="utf-8")
    return path


def render_nav_block(modules: list[str]) -> str:
    """Render the YAML nav fragment for the API Reference section."""
    lines = [
        "  - API Reference:",
        "      - Overview: api/index.md",
    ]
    for module in modules:
        lines.append(f"      - {module_title(module)}: api/{module}.md")
    return "\n".join(lines)


def update_mkdocs_nav(mkdocs_path: Path, modules: list[str]) -> None:
    """Replace the autogenerated API nav section in ``mkdocs.yml``."""
    text = mkdocs_path.read_text(encoding="utf-8")
    if NAV_START not in text or NAV_END not in text:
        raise ValueError(
            f"{mkdocs_path} must contain {NAV_START} and {NAV_END} markers for API navigation."
        )
    pattern = re.compile(
        rf"(\s*{re.escape(NAV_START)}\n)(.*?)(\s*{re.escape(NAV_END)})",
        re.DOTALL,
    )
    replacement = f"\n{NAV_START}\n{render_nav_block(modules)}\n  {NAV_END}"
    updated, count = pattern.subn(replacement, text, count=1)
    if count != 1:
        raise ValueError(f"Failed to update API nav in {mkdocs_path}")
    mkdocs_path.write_text(updated, encoding="utf-8")


def generate_all(project_root: Path) -> list[Path]:
    """Generate all API stub files and refresh ``mkdocs.yml`` navigation.

    Args:
        project_root: Repository root.

    Returns:
        List of paths written or updated.
    """
    package_dir = project_root / "src" / PACKAGE_NAME
    api_dir = project_root / "docs" / "api"
    api_dir.mkdir(parents=True, exist_ok=True)

    modules = discover_modules(package_dir)
    if not modules:
        raise RuntimeError(f"No modules discovered under {package_dir}")

    written: list[Path] = []
    written.append(write_index(api_dir, modules))
    for module in modules:
        written.append(write_stub(api_dir, module))

    # Remove stale stubs for deleted modules.
    for path in api_dir.glob("*.md"):
        if path.name == "index.md":
            continue
        if path.stem not in modules:
            path.unlink()
            written.append(path)  # record deletion

    update_mkdocs_nav(project_root / "mkdocs.yml", modules)
    written.append(project_root / "mkdocs.yml")
    return written


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    paths = generate_all(root)
    print(f"Generated {len(paths)} API stub artifacts under docs/api/")
    for path in sorted(paths):
        print(f"  {path.relative_to(root)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
