apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: file.uploaded
  labels:
    strimzi.io/cluster: genomic-kafka
spec:
  partitions: 12
  replicas: 3
  config:
    retention.ms: 604800000
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: search.requested
...
